
import { StyleSheet } from 'react-native';
import {Metrics} from "../../configs/Theme";

export default StyleSheet.create({
    schedule_view:{
        flex:1,
        backgroundColor:"#ECECEE"
    },
    carousels_view:{
        height:66,
        marginBottom:6
    },
    item_select_view:{
        display:'flex',
        backgroundColor:"#D63649",
        flexDirection:'column',
        alignItems:'center',
        width:60,
        height:62,
        justifyContent:'center'
    },
    item_view:{
        display:'flex',
        backgroundColor:"#13151C",
        flexDirection:'column',
        alignItems:'center',
        justifyContent:'center',
        width:64,
        height:66
    },
    item_view2:{
        paddingTop:16,
        marginLeft:18,
        marginRight:18,
        flexDirection:'column'
    },
    top_txt1:{
        color:"#444444",
        fontSize:14
    },
    schedule_middle_view:{
        flexDirection:'row',
        paddingTop:12,
        paddingBottom:12
    },
    time_txt:{
        color:"#AAAAAA",
        fontSize:12
    },
    schedule_bottom_view:{
        flexDirection:'row',
        marginBottom:16
    },
    race_price:{
        color:"#444444",
        fontSize:12
    },
    selected_view:{
        backgroundColor:"#ECECEE",
        paddingTop:10
    },
    line:{
        backgroundColor:"#CCCCCC",
        height:1,
        width:Metrics.screenWidth - 36,
        marginTop:10,
        marginBottom:12,
        alignSelf:'center'
    },
    selected_middle_view:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        marginLeft:17,marginRight:17
    },
    selected_bottom_view:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        marginLeft:17,marginRight:17,
        paddingBottom:14
    },
    cloumn_view:{
        flexDirection:'column'
    },
    top_txt2:{
        color:"#888888",
        fontSize:14,
        marginTop:4
    },
    day_txt:{
        color:"#FFFFFF",
        fontSize:16
    },
    week_txt:{
        color:"#FFFFFF",
        fontSize:12
    },
    structure_view:{
        height:40,
        backgroundColor:'white',
        flexDirection:'row',
        alignItems:'center',
        paddingLeft:17,
        paddingRight:17
    },
    structure_txt:{
        color:"#444444",
        fontSize:14
    },
    problem_view:{
        marginTop:4,
        backgroundColor:'white',
        paddingTop:12,
        paddingBottom:7,
        flexDirection:'row',
        alignItems:'center',
        paddingLeft:17,
        paddingRight:17
    },
    calendar_view:{
        backgroundColor:'white',
        paddingBottom:26,
        flexDirection:'row',
        alignItems:'center',
        paddingLeft:17,
        paddingRight:17,
        paddingTop:7
    },
    problem_txt:{
        color:"#888888",
        fontSize:14
    }

})

