
import { StyleSheet } from 'react-native';
import {Colors, Metrics, px2dp, px2sp, wh} from "../../configs/Theme";

export default StyleSheet.create({
    schedule_view:{
        flex:1,
        backgroundColor:Colors._1A1
    },
    carousels_view:{
        height:px2dp(118)
    },
    item_select_view:{
        display:'flex',
        backgroundColor:"#D63649",
        flexDirection:'column',
        alignItems:'center',
        width:70,
        height:62,
        justifyContent:'center'
    },
    item_view:{
        alignItems:'center',
        justifyContent:'center',
        width:70,
        height:66
    },
    item_view2:{
        paddingTop:px2dp(22),
        paddingLeft:px2dp(18),
        paddingRight:px2dp(20),
        backgroundColor:Colors._303
    },
    top_txt1:{
        fontSize: px2sp(24),
        color: Colors._FFE
    },
    schedule_middle_view:{
        flexDirection:'row',
        paddingTop:12,
        paddingBottom:12
    },
    time_txt:{
        color:"#AAAAAA",
        fontSize:12
    },
    schedule_bottom_view:{
        flexDirection:'row',
        alignItems:'center',
        marginBottom:16
    },
    race_price:{
        color:"#444444",
        fontSize:12
    },
    selected_view:{
        paddingTop:px2dp(18),
        backgroundColor:'#252629'
    },
    line:{
        backgroundColor:"#CCCCCC",
        height:1,
        width:Metrics.screenWidth - 36,
        marginTop:10,
        marginBottom:12,
        alignSelf:'center'
    },
    selected_middle_view:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        marginLeft:17,marginRight:17
    },
    selected_bottom_view:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        marginLeft:17,marginRight:17,
        paddingBottom:14
    },
    cloumn_view:{
        flexDirection:'row',
        justifyContent:'space-between'
    },
    top_txt2:{
        color:"#888888",
        fontSize:14,
        marginTop:4
    },
    day_txt:{
        color:Colors._998,
        fontSize:px2sp(28),
        lineHeight:18
    },
    week_txt:{
        color:Colors._998,
        fontSize:px2sp(24),
        lineHeight:18
    },
    day_txt_light:{
        color:Colors._FFE,
        fontSize:px2sp(28),
        lineHeight:18
    },
    week_txt_light:{
        color:Colors._FFE,
        fontSize:px2sp(24),
        lineHeight:18
    },
    structure_view:{
        height:40,
        backgroundColor:'white',
        flexDirection:'row',
        alignItems:'center',
        paddingLeft:17,
        paddingRight:17
    },
    structure_txt:{
        color:"#444444",
        fontSize:14
    },
    problem_view:{
        marginTop:4,
        backgroundColor:'white',
        paddingTop:12,
        paddingBottom:7,
        flexDirection:'row',
        alignItems:'center',
        paddingLeft:17,
        paddingRight:17
    },
    calendar_view:{
        backgroundColor:'white',
        paddingBottom:26,
        flexDirection:'row',
        alignItems:'center',
        paddingLeft:17,
        paddingRight:17,
        paddingTop:7
    },
    problem_txt:{
        color:"#888888",
        fontSize:14
    },
    btnRemark:{
        borderColor:'#998E72',
        borderRadius:px2dp(4),
        borderWidth: px2dp(2),
        ...wh(210,54),
        alignItems:'center',
        justifyContent:'center',
        marginRight:px2dp(20)
    }

})

