
import { StyleSheet } from 'react-native';
import {Metrics} from "../../configs/Theme";

export default StyleSheet.create({
    schedule_view:{
        flex:1,
        backgroundColor:"#ECECEE"
    },
    carousels_view:{
        height:66,
        marginBottom:6
    },
    item_select_view:{
        display:'flex',
        backgroundColor:"#D63649",
        flexDirection:'column',
        alignItems:'center',
        width:60,
        height:62
    },
    item_view:{
        display:'flex',
        backgroundColor:"#13151C",
        flexDirection:'column',
        alignItems:'center',
        width:64,
        height:66
    },
    item_view2:{
        paddingTop:16,
        paddingBottom:16,
        marginLeft:18,
        marginRight:18,
        flexDirection:'column'
    },
    top_txt1:{
        color:"#444444",
        fontSize:14,
        fontWeight:'bold'
    },
    schedule_middle_view:{
        flexDirection:'row',
        paddingTop:12,
        paddingBottom:12
    },
    time_txt:{
        color:"#AAAAAA",
        fontSize:12
    },
    schedule_bottom_view:{
        flexDirection:'row',
        marginBottom:16
    },
    race_price:{
        color:"#444444",
        fontSize:12
    },
    selected_view:{
        backgroundColor:"#ECECEE",
        paddingTop:10,
        paddingBottom:14,
        paddingLeft:18,
        paddingRight:18
    },
    line:{
        backgroundColor:"#CCCCCC",
        height:1,
        width:Metrics.screenWidth - 36,
        marginTop:10,
        marginBottom:12
    },
    selected_middle_view:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between'
    },
    selected_bottom_view:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between'
    },
    cloumn_view:{
        flexDirection:'column'
    },
    top_txt2:{
        color:"#888888",
        fontSize:14,
        marginTop:4
    }

})

